name: Run Main Script

on:
  push:
    branches:
      - test-workflow

jobs:
  run:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - run: python src/view/app.py


    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: python src/view/app.py
