name: Run Main Script

on:
  push:
    branches:
      - test-workflow

jobs:
  run:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10


    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: python src/view/app.py
